// Shared port/protocol reference data used by every game on this dashboard.
// Source: CompTIA Common Ports Reference (A+ / Network+ / Security+ / CySA+)
const PORT_DATA = [
  { port: "20/21",      protocol: "FTP",                 transport: "TCP",     use: "File transfer (data / control)" },
  { port: "22",         protocol: "SSH / SFTP / SCP",     transport: "TCP",     use: "Secure remote access, secure file transfer" },
  { port: "23",         protocol: "Telnet",               transport: "TCP",     use: "Unencrypted remote access" },
  { port: "25",         protocol: "SMTP",                 transport: "TCP",     use: "Email sending" },
  { port: "53",         protocol: "DNS",                  transport: "TCP/UDP", use: "Name resolution" },
  { port: "67/68",      protocol: "DHCP",                 transport: "UDP",     use: "IP address assignment" },
  { port: "69",         protocol: "TFTP",                 transport: "UDP",     use: "Trivial file transfer" },
  { port: "80",         protocol: "HTTP",                 transport: "TCP",     use: "Unencrypted web traffic" },
  { port: "110",        protocol: "POP3",                 transport: "TCP",     use: "Email retrieval" },
  { port: "123",        protocol: "NTP",                  transport: "UDP",     use: "Time synchronization" },
  { port: "135",        protocol: "RPC",                  transport: "TCP",     use: "Remote procedure calls (Windows)" },
  { port: "137-139",    protocol: "NetBIOS",               transport: "TCP/UDP", use: "Legacy Windows file/print sharing" },
  { port: "143",        protocol: "IMAP",                 transport: "TCP",     use: "Email retrieval (syncs across devices)" },
  { port: "161/162",    protocol: "SNMP",                  transport: "UDP",     use: "Network device monitoring" },
  { port: "389",        protocol: "LDAP",                 transport: "TCP/UDP", use: "Directory services" },
  { port: "443",        protocol: "HTTPS",                transport: "TCP",     use: "Encrypted web traffic" },
  { port: "445",        protocol: "SMB",                  transport: "TCP",     use: "Windows file sharing" },
  { port: "3389",       protocol: "RDP",                  transport: "TCP",     use: "Remote Desktop" },
  { port: "465",        protocol: "SMTPS",                transport: "TCP",     use: "Encrypted SMTP" },
  { port: "587",        protocol: "SMTP (submission)",    transport: "TCP",     use: "Authenticated mail submission" },
  { port: "636",        protocol: "LDAPS",                transport: "TCP",     use: "Encrypted LDAP" },
  { port: "993",        protocol: "IMAPS",                transport: "TCP",     use: "Encrypted IMAP" },
  { port: "995",        protocol: "POP3S",                transport: "TCP",     use: "Encrypted POP3" },
  { port: "514",        protocol: "Syslog",               transport: "UDP",     use: "Log forwarding (SIEM/log analysis)" },
  { port: "3306",       protocol: "MySQL",                transport: "TCP",     use: "Database traffic" },
  { port: "1433",       protocol: "MS SQL",               transport: "TCP",     use: "Database traffic" },
  { port: "5060/5061",  protocol: "SIP",                  transport: "TCP/UDP", use: "VoIP signaling (plain / TLS)" }
];
